-- Customer Behavior & Sales Analytics
-- SQL Analysis
-- Purpose: Analyze customer shopping behavior and sales performance


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM customer_shopping
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than
--     the average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer_shopping
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer_shopping
  );


-- Q3. Which are the top 5 products with the highest average review rating?
WITH product_ratings AS (
    SELECT
        item_purchased,
        ROUND(AVG(review_rating), 2) AS average_rating
    FROM customer_shopping
    GROUP BY item_purchased
)
SELECT
    item_purchased,
    average_rating
FROM product_ratings
ORDER BY average_rating DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between Standard
--     and Express shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer_shopping
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more?
--     Compare average spending, total revenue, and customer count
--     between subscribed and non-subscribed customers.
SELECT
    subscription_status,
    ROUND(AVG(purchase_amount), 2) AS average_spending,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    COUNT(customer_id) AS total_customers
FROM customer_shopping
WHERE subscription_status IN ('Yes', 'No')
GROUP BY subscription_status
ORDER BY total_revenue DESC,
         average_spending DESC;


-- Q6. Which 5 products have the highest percentage of purchases
--     with a discount applied?
SELECT
    item_purchased,
    ROUND(
        SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*) * 100,
        2
    ) AS discount_rate
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal customers
--     based on their number of previous purchases.
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping
)
SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_count AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_count
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers
--     (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS revenue_contribution
FROM customer_shopping
GROUP BY age_group
ORDER BY revenue_contribution DESC;

